In [ ]:
#Assume Null Hypothesis as Ho: the defective % does not varies by center
#Alternate Hypothesis as Ha: the defective % varies by center

Chi Square test of independence for categorical data

In [1]:
import pandas as pd
import numpy as np
import scipy
from scipy import stats
import statsmodels.api as sm
from scipy.stats import chi2_contingency
from scipy.stats import norm

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Costomer+OrderForm.csv to Costomer+OrderForm.csv


In [3]:
data = pd.read_csv('Costomer+OrderForm.csv')
data.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [4]:
data.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [5]:
data.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [6]:
data.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [7]:
data.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [8]:
#preparing a contingency table
observed = np.array([[271, 267, 269, 280], [29, 33, 31, 20]])
observed

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [9]:
stats, p, dof, expfreq = stats.chi2_contingency(observed)
print( stats, '\n', p, '\n', dof, '\n', expfreq)

3.858960685820355 
 0.2771020991233135 
 3 
 [[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


In [11]:
alpha = 0.05 #given
print('Chi2 test value is ', p)
if p < alpha:
  print('Reject Null Hypothesis')
else:
  print('Accept Null Hypothesis')

Chi2 test value is  0.2771020991233135
Accept Null Hypothesis


# **As we failed to reject null hypothesis, customer order forms defective % does not varies by centre.**